#!/bin/sh

# Stop on errors
set -e

# get repo key
curl -fsSL http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key | sudo apt-key add -

#download appropriate lists file
cd /etc/apt/sources.list.d/
sudo wget http://repo.mosquitto.org/debian/mosquitto-stretch.list

#update caches and install
apt-cache search mosquitto
sudo apt-get update
sudo apt-get install libmosquitto-dev mosquitto mosquitto-clients
